// Generated by CoffeeScript 1.8.0
(function() {
  var debug;

  debug = require('debug');

  module.exports = function(ns) {
    return {
      debug: debug("messaging:" + ns + ":debug"),
      info: debug("messaging:" + ns + ":info"),
      warn: debug("messaging:" + ns + ":warn"),
      error: debug("messaging:" + ns + ":error")
    };
  };

}).call(this);
